# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/aurora/.local/share/unreal/5.6.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	BirdGame-Android-DebugGame  \
	BirdGame-Android-Development  \
	BirdGame-Android-Shipping  \
	BirdGame-Linux-DebugGame  \
	BirdGame-Linux-Development  \
	BirdGame-Linux-Shipping  \
	BirdGame-LinuxArm64-DebugGame  \
	BirdGame-LinuxArm64-Development  \
	BirdGame-LinuxArm64-Shipping  \
	BirdGame \
	BirdGameEditor-Linux-DebugGame  \
	BirdGameEditor-Linux-Development  \
	BirdGameEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BirdGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BirdGameEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

BirdGame-Android-DebugGame:
	 $(BUILD) BirdGame Android DebugGame  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-Android-Development:
	 $(BUILD) BirdGame Android Development  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-Android-Shipping:
	 $(BUILD) BirdGame Android Shipping  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-Linux-DebugGame:
	 $(BUILD) BirdGame Linux DebugGame  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-Linux-Development:
	 $(BUILD) BirdGame Linux Development  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-Linux-Shipping:
	 $(BUILD) BirdGame Linux Shipping  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-LinuxArm64-DebugGame:
	 $(BUILD) BirdGame LinuxArm64 DebugGame  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-LinuxArm64-Development:
	 $(BUILD) BirdGame LinuxArm64 Development  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame-LinuxArm64-Shipping:
	 $(BUILD) BirdGame LinuxArm64 Shipping  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGame: BirdGame-Linux-Development

BirdGameEditor-Linux-DebugGame:
	 $(BUILD) BirdGameEditor Linux DebugGame  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGameEditor-Linux-Development:
	 $(BUILD) BirdGameEditor Linux Development  -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" $(ARGS)

BirdGameEditor: BirdGameEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/aurora/Documents/University/AGP41024/Assignments/BirdGame/BirdGame.uproject" -Game 

.PHONY: $(TARGETS)
